- name: Deploy Maven Artifact
  hosts: web
  become: no

  tasks:
    - name: Ensure app directory exists
      file:
        path: /var/lib/jenkins/workspace/dev/apps
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Copy JAR file
      copy:
        src: /var/lib/jenkins/workspace/dev/myapp/target/myapp-1.0-SNAPSHOT.jar
        dest: /var/lib/jenkins/workspace/dev/apps/myapp-1.0-SNAPSHOT.jar

    - name: Run application
      shell: nohup java -jar /var/lib/jenkins/workspace/dev/apps/myapp-1.0-SNAPSHOT.jar &
      args:
        chdir: /var/lib/jenkins/workspace/dev/apps
